// Known company -> domain map for logo lookup; anything unknown falls back
// to a guessed "<name>.com". Callers should hide the <img> on error so a
// bad guess degrades to just the company name.
const companyDomains: Record<string, string> = {
  google: "google.com",
  amazon: "amazon.com",
  meta: "meta.com",
  facebook: "facebook.com",
  microsoft: "microsoft.com",
  apple: "apple.com",
  adobe: "adobe.com",
  bloomberg: "bloomberg.com",
  uber: "uber.com",
  linkedin: "linkedin.com",
  netflix: "netflix.com",
  yelp: "yelp.com",
  palantir: "palantir.com",
  oracle: "oracle.com",
  salesforce: "salesforce.com",
  airbnb: "airbnb.com",
  stripe: "stripe.com",
  spotify: "spotify.com",
  twitter: "x.com",
  x: "x.com",
  tesla: "tesla.com",
  nvidia: "nvidia.com",
  intel: "intel.com",
  ibm: "ibm.com",
  paypal: "paypal.com",
  dropbox: "dropbox.com",
  snapchat: "snap.com",
  snap: "snap.com",
  tiktok: "tiktok.com",
  bytedance: "bytedance.com",
  atlassian: "atlassian.com",
  samsung: "samsung.com",
  cisco: "cisco.com",
  vmware: "vmware.com",
  "goldman sachs": "goldmansachs.com",
  "morgan stanley": "morganstanley.com",
  "jp morgan": "jpmorgan.com",
  visa: "visa.com",
  walmart: "walmart.com",
  flipkart: "flipkart.com",
  swiggy: "swiggy.com",
  zomato: "zomato.com",
  paytm: "paytm.com",
  infosys: "infosys.com",
  tcs: "tcs.com",
  wipro: "wipro.com",
  accenture: "accenture.com",
  qualcomm: "qualcomm.com",
  expedia: "expedia.com",
  doordash: "doordash.com",
  lyft: "lyft.com",
  pinterest: "pinterest.com",
  reddit: "reddit.com",
  twitch: "twitch.tv",
  shopify: "shopify.com",
  square: "block.xyz",
  robinhood: "robinhood.com",
  coinbase: "coinbase.com",
};

export function companyLogoUrl(name: string, size = 64): string {
  const key = name.trim().toLowerCase();
  const domain = companyDomains[key] ?? `${key.replace(/\s+/g, "")}.com`;
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`;
}
